version: "3.8"

services:
    app:
        build: .
        ports:
            - "5005:5005"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=development
